# Use a Node base image
FROM node:latest

# Set the working directory
WORKDIR /app/frontend
# copy frontend/ to docker /app/frontend
COPY . .

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Build the application
RUN npm run build

# Start the application
CMD ["npm", "run", "dev"]

