version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app/frontend  # Mount the directory so changes get reflected immediately
      