# base image with jdk 21
FROM openjdk:21-ea-11-jdk-slim AS build

# Install Maven manually
RUN apt-get update && apt-get install -y maven

# Set the working directory in the container
WORKDIR /app

# Deal with dependencies first -> caching after first build 
COPY pom.xml /app
RUN mvn dependency:go-offline

COPY . /app
# Package the application
RUN mvn package -Dmaven.test.skip

# For the application stage, use the same Java 21 base image
FROM openjdk:21-ea-11-jdk-slim

# Copy the built jar from the build stage
COPY --from=build /app/target/cs520-0.0.1-SNAPSHOT.jar /app.jar
