import './globals.css';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';

const font = Open_Sans({ subsets: ['latin'] });
import { ThemeProvider } from '@/components/providers/theme-provider';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'UMassenger',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressContentEditableWarning>
      <body className={cn(font.className, 'bg-while dark:bg-[#313338]')}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          storageKey="UMassenger"
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
